<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="THINK-M4480-11" name="test_cases.ChangePasswordAccountTest" tests="5" failures="2" timestamp="30 Mar 2015 17:37:36 GMT" time="0.009" errors="1">
  <testcase name="testLogin" time="0.002" classname="test_cases.ChangePasswordAccountTest">
    <error type="org.junit.ComparisonFailure" message="expected:&lt;[a]&gt; but was:&lt;[A]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[a]> but was:<[A]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at test_cases.ChangePasswordAccountTest.testLogin(ChangePasswordAccountTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testLogin -->
  <testcase name="testLogout" time="0.000" classname="test_cases.ChangePasswordAccountTest"/>
  <testcase name="SuccessToChangeUserAccountPassword" time="0.000" classname="test_cases.ChangePasswordAccountTest"/>
  <testcase name="testChangePassword" time="0.000" classname="test_cases.ChangePasswordAccountTest"/>
  <testcase name="SuccessToChangeUserAccountPassword" time="0.007" classname="test_cases.ChangePasswordAccountTest"/>
</testsuite> <!-- test_cases.ChangePasswordAccountTest -->
